#!/usr/bin/env sh

# check if connection to k8s API is ready
/opt/okeutil/check-oke-connection.sh
RESULT=$?
if [ $RESULT -eq 0 ]
then
  # execute
  for YAML in "$@"
  do
      if [ -f "$YAML" ]
      then
          kubectl delete -f "$YAML"
      else
          echo "File [$YAML] not found"
          exit 1
      fi
  done
fi