#!/bin/bash

# check if connection to k8s API is ready
/opt/okeutil/check-oke-connection.sh
RESULT=$?
if [ $RESULT -eq 0 ]
then
  # execute
  for YAML in "$@"
  do
    case "$YAML" in
      http://)
        ;;
      https://)
        ;;
      *)
        if [ ! -f "$YAML" ]
        then
          echo "File [$YAML] not found"
          exit 1
        fi
        ;;
    esac
    kubectl delete -f "$YAML"
  done
fi